# This is a config for E2B sandbox template.
# You can use template ID (hwsia9gqrprl5x50vg3x) or template name (surf-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("surf-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("surf-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('surf-nextjs-test-2')

team_id = "decc1d32-feb5-4d92-96d2-c5c61e215c86"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "surf-nextjs-test-2"
template_id = "hwsia9gqrprl5x50vg3x"
